---
title: "Workflow Cost Report"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
library(shiny)
library(data.table)
library(DT)
library(stringr)
library(ComplexHeatmap)
library(circlize)
library(ggplot2)
library(patchwork)

mainTbl <- fread("~/Desktop/Projects/CostMonitor/data/workflowData.tsv")
mainTbl <- mainTbl[cost != "N/A"]
mainTbl <- mainTbl[, c("workflow", "workflowId", "sample", "entityType", "cost", "costType", "status", "statusLastChangedDate", "workflowVersion")]
mainTbl[, cost := as.numeric(cost)]
```

Sidebar {.sidebar}
=====================================

```{r progress_heatmap_inputs}
selectInput("sampleType", "Entities to check",
              choices = unique(mainTbl$entityType),
              selected = unique(mainTbl$entityType)[1])

# 1. Initialize the checkboxGroup empty so it doesn't crash on boot
checkboxGroupInput("wfCheck", "Workflows to show", choices = NULL)

# 2. Use a reactive observer to update the choices seamlessly whenever sampleType changes
observeEvent(input$sampleType, {
  wfChoices <- unique(mainTbl[entityType == input$sampleType]$workflow)
  updateCheckboxGroupInput(getDefaultReactiveDomain(), "wfCheck",
    choices = wfChoices,
    selected = wfChoices
  )
})
```

Current Sample Status
=====================================

Column 1 {data-width=300}
--------

### Sample Status Heatmap {data-height=600}

```{r progress_heatmap}
# color palette for progress heatmap, no need to change
pal <- colorRampPalette(c("skyblue", "gray", "red", "green"))(4)
colors = structure(pal, names = c("0", "1", "2", "3"))

renderPlot({
  req(input$wfCheck)
  mapTable <- dcast(
    unique(mainTbl[entityType == input$sampleType & workflow %in% input$wfCheck][order(status, decreasing = TRUE)], by = c("workflow", "sample"))[, c("workflow", "sample", "status")][, status := as.integer(status == "Succeeded")],
    sample ~ workflow,
    value.var = "status"
  )
  wfCols <- colnames(mapTable)[-1]
  mapTable$progress <- rowSums(mapTable[,-1], na.rm=TRUE)
  setorderv(mapTable, c("progress", wfCols), order = -1)

  # logic for coloring table
  mapTable[, (wfCols) := lapply(
    .SD,
    function(col) fifelse(is.na(col), 1, col + 2)
  ), .SDcols = wfCols]
  setorderv(mapTable, wfCols, order = -1)

  Heatmap(
    mapTable[, wfCols, with = FALSE],
          # width = unit(8, "cm"),
          # height = unit(12, "cm"),
          col = colors,
          cluster_columns = FALSE,
          cluster_rows = FALSE,
          column_names_side = "top",
          column_names_rot = 45,
          column_names_gp = gpar(fontsize = 10, fontface = "bold"),
          rect_gp = gpar(col = "darkgray", lwd = 0.1),
          border_gp = gpar(col = "black", lwd = 0.2),
          heatmap_legend_param = list(
            title = "Status",
            at = 0:3,
            color_bar = "discrete",
            labels = c("G2C processed", "not started", "failed", "complete"),
            labels_gp = gpar(fontsize = 10),
            title_gp = gpar(fontsize = 12, fontface = "bold"),
            grid_height = unit(8, "mm"),
            grid_width = unit(8, "mm")
          ),
          left_annotation = rowAnnotation(
            title = anno_block(
              labels = c(paste0(nrow(mapTable), "\nTotal Samples")),
              labels_rot = 0,
              width = unit(3, "cm"),
              gp = gpar(col = NA)
            )
          )
  )
})
```

### Cost Distribution {data-height=400}

```{r}
renderPlot({
  tmpTbl <- mainTbl[entityType == input$sampleType][, .(total_cost = round(sum(as.numeric(cost)), 2)), by = c("workflow", "sample")]
  tmpTbl <- tmpTbl[workflow %in% input$wfCheck][, .(total_cost = sum(total_cost)), by = sample]
  
  sampStatus <- unique(mainTbl[workflow %in% input$wfCheck & 
                                 entityType == input$sampleType &
                                 status == "Succeeded", c("workflow", "sample")])
  numWorkflows <- uniqueN(sampStatus$workflow)
  sampStatus <- sampStatus[,.(count = .N), by = sample]
  completeSamples <- sampStatus[count == numWorkflows]$sample
  
  
  ggplot(rbind(tmpTbl[, .(type = "All"), c("total_cost")],
               tmpTbl[sample %in% completeSamples, .(type = "Complete"), c("total_cost")]),
         aes(total_cost, type)) +
    geom_boxplot() +
    ylab("") +
    xlab("Total Cost per Sample ($)") +
    scale_x_continuous(limits = c(0, 15)) +
    ggtitle("Sample Costs") +
    theme_linedraw() +
    theme(text = element_text(size=14))
})
```

Column 2 {data-width=700}
--------

### Sample Status Table

```{r}
renderDataTable({
  req(input$wfCheck)

  tmpStatus <- dcast(
    unique(mainTbl[entityType == input$sampleType][order(status, decreasing = TRUE)], 
           by = c("workflow", "sample"))[, c("workflow", "sample", "status")][, status := as.integer(status == "Succeeded")],
    sample ~ workflow,
    value.var = "status"
  )
  wfCols <- colnames(tmpStatus)[-1]
  tmpStatus$progress <- rowSums(tmpStatus[,-1], na.rm=TRUE)
  setorderv(tmpStatus, c("progress", wfCols), order = -1)
  invStatus <- copy(tmpStatus)
  wfCols <- colnames(tmpStatus)[-1]
  invStatus[, (wfCols) := lapply(.SD, function(col) as.integer(col == 0)), .SDcols = wfCols]
  tmpSumm <- rbind(colSums(tmpStatus[, -c("sample", "progress")], na.rm=TRUE),
                   colSums(invStatus[, -c("sample", "progress")], na.rm=TRUE))
  rownames(tmpSumm) <- c("Success", "Fail")
  datatable(t(tmpSumm[, input$wfCheck]))
})
```

### Sample Cost Table

```{r}
renderDataTable({
  req(input$wfCheck)
  
  tmpCostTbl <- mainTbl[entityType == input$sampleType & workflow %in% input$wfCheck][, .(total_cost = round(sum(as.numeric(cost)), 2)), by = c("workflow", "sample")]
  
  
  sampByWf <- dcast(tmpCostTbl, sample ~ workflow, value.var = "total_cost")
  sampByWf[, total := round(rowSums(.SD, na.rm = TRUE), 2), .SDcols = colnames(sampByWf)[-1]]
  sampByWf
})
```

Workflow Cost Estimates
=====================================

Column 1 {data-width=350}
--------

### Workflow Distribution

```{r workflow_dist, echo=FALSE}
renderPlot({
  req(input$wfCheck)
  tmpCostTbl <- mainTbl[entityType == input$sampleType & workflow %in% input$wfCheck][, .(total_cost = round(sum(as.numeric(cost)), 2)), by = c("workflow", "sample")]
  tmpCostTbl <- tmpCostTbl[workflow %in% input$wfCheck]

  ggplot(tmpCostTbl, aes(total_cost, workflow)) +
    geom_boxplot() +
    ylab("") +
    scale_x_continuous(limits = c(0, 10)) +
    ggtitle("Workflow Costs per Sample ($)") +
    theme_linedraw() +
    theme(text = element_text(size = 14))
})
```

### Workflow Cost Table

```{r}
renderDataTable({
  req(input$wfCheck)
  tmpCostTbl <- mainTbl[entityType == input$sampleType & workflow %in% input$wfCheck][, .(total_cost = round(sum(as.numeric(cost)), 2)), by = c("workflow", "sample")]
  tmpCostTbl <- tmpCostTbl[workflow %in% input$wfCheck]
  datatable(tmpCostTbl[, .(avg_cost = mean(total_cost), sd_cost = sd(total_cost),
                         total = sum(total_cost)), by = workflow]) %>% formatRound(c(2:4), 2)
})

```

Column 2 {data-width=650}
--------


### All Workflows 

```{r whole_table, echo=FALSE}
renderDataTable({
  req(input$sampleType)
  datatable(mainTbl[entityType == input$sampleType & workflow %in% input$wfCheck])
})
```

### Workflow Table

```{r workflow_table, echo=FALSE}
renderDataTable({
  tmpCost <-   mainTbl[entityType == input$sampleType & workflow %in% input$wfCheck][, .(total_cost = sum(cost)), by = c("workflow", "workflowVersion", "sample")][
    ,.(avg_cost = mean(total_cost), sd_cost = sd(total_cost), count = .N, total_cost = sum(total_cost)),
    by = c("workflow", "workflowVersion")][order(workflow, workflowVersion)
  ]
  datatable(tmpCost) %>% formatRound(c(3,4,6), 2)
})
```

Data Usage
===========

Column 1
-----------

### Storage Cost Estimate
```{r}
storData <- fread("../data/StorageEstimate.tsv")
sizeFactor <- 1024 ^ 4 # TB
sizeUnit <- "TB"
liveCost <- round(storData$`usage.live-object`[1] / sizeFactor, 2)
softCost <- round(storData$`usage.soft-deleted-object`[1] / sizeFactor, 2)

renderPlot({
  pie(c(liveCost, softCost),
      labels = c(paste0(liveCost, sizeUnit, " (Live Objects)"),
                 paste0(softCost, sizeUnit, " (Soft-delete Objects)")),
      main = paste0("Storage Cost (Monthly Total = $", storData$estimate, ")"),
      cex = 2.4,
      cex.main = 2.9)
})
```
